-- ===========================================================================
-- 0013 — proving you are allowed to pay for this order
--
-- Phase B2.2a. One column, one function, and a changed argument list. No
-- Stripe, no Edge Function, no secret, no scheduler.
--
-- THE PROBLEM
--
-- A guest has no account, so nothing about a session can authorise them. The
-- only things they hold today are the order number and the amounts — and
-- `SI-2026-001000` is a counter, not a secret. Building a payment on it would
-- let anybody open a payment session for anybody else's order and read its
-- contents. `orders.id`, `customer_email`, `client_hash` and `request_id` are
-- no better: none of them is both secret and bound to one order.
--
-- So an order gets a capability: a random secret whose hash is stored here and
-- whose plaintext lives only in the browser that placed it.
--
-- THE PART THAT DECIDED THE DESIGN: THE TOKEN TRAVELS FORWARD, NOT BACK
--
-- The obvious version — the server mints the token and returns it once — has
-- a hole that cannot be patched afterwards. If the HTTP response is lost after
-- the transaction committed, the order exists, the stock is held, and the only
-- copy of the plaintext is gone. The guest can never pay, and the reservation
-- sits on a one-of-a-kind figure for twenty minutes.
--
-- Re-issuing a token on retry would fix that and open a worse hole: whoever
-- knows a `request_id` could then mint themselves a capability.
--
-- Instead the **caller** generates the token and sends it forward, and this
-- function only ever stores its hash. A lost response destroys nothing,
-- because the browser had the secret before it made the call. A retry with the
-- same `request_id` therefore does not need a new token — it **proves** it
-- holds the old one, and the existing order is handed back.
--
-- Client-chosen entropy is safe here, and that is worth being explicit about:
-- a caller who picks a weak token weakens only the capability for the order
-- they are creating, which they already control. It gives them nothing against
-- anybody else's order, because the token must hash to the value stored on
-- *that* row.
--
-- FOR B2.2b, AND NOT NEGOTIABLE: `p_user_id` IS NEVER A PAYLOAD FIELD
--
-- `authorize_order_payment()` trusts whatever user id it is handed. That is
-- safe only because its one caller will be an Edge Function that derives the
-- id itself. That function must read the `Authorization` header, verify the
-- JWT server-side, and take the id from the verified claims — never from the
-- request body. A body containing `{"user_id": "<somebody else's uuid>"}` must
-- carry no authority whatsoever. With no valid JWT the id is NULL and the
-- capability token is the only way in.
--
-- ADDITIVE, AND SAFE TO APPLY BEFORE THE NEW BUILD IS LIVE. One nullable
-- column, two new functions, and the previous `create_order()` left in place
-- as a temporary shim so the running deployment keeps working. Existing orders
-- stay valid: the column is NULL for them, which simply means "no capability
-- was issued", and nothing reads it for those rows.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. The capability, as a hash
--
-- SHA-256 of the token, hex. Not the token, and nothing reversible: a database
-- dump must not hand anybody the ability to pay for, or read, other people's
-- orders.
--
-- `sha256()` is core PostgreSQL, so this needs no extension. It is the same
-- primitive `request_client_hash()` already uses.
--
-- Nullable, and deliberately without a "created at": the order already has
-- `placed_at`, and the token has exactly the same lifetime as the order's
-- unpaid window. A second timestamp would say nothing the first does not.
-- ---------------------------------------------------------------------------
alter table public.orders
  add column if not exists payment_token_hash text;

alter table public.orders
  drop constraint if exists orders_payment_token_hash_format;

-- 64 hex characters or nothing. A wrong-length value is a bug, not a token.
alter table public.orders
  add constraint orders_payment_token_hash_format
    check (payment_token_hash is null or payment_token_hash ~ '^[0-9a-f]{64}$');

comment on column public.orders.payment_token_hash is
  'SHA-256 of the capability that lets whoever placed this order pay for it. The plaintext is generated by the caller, sent forward, and never stored or returned — see migration 0013. NULL on orders placed before B2.2a.';


-- ---------------------------------------------------------------------------
-- 2. Set once, never rewritten
--
-- Replaces the trigger from 0010/0011 in place. A capability that could be
-- overwritten would be a capability anybody with write access could mint, and
-- the whole point is that not even this database can produce the plaintext.
-- ---------------------------------------------------------------------------
create or replace function public.orders_protect_immutable()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.order_number   is distinct from old.order_number
     or new.request_id  is distinct from old.request_id
     or new.placed_at   is distinct from old.placed_at
     or new.currency    is distinct from old.currency
     or new.customer_email  is distinct from old.customer_email
     or new.items_subtotal  is distinct from old.items_subtotal
     or new.shipping_amount is distinct from old.shipping_amount
     or new.discount_amount is distinct from old.discount_amount
     or new.total_amount    is distinct from old.total_amount
     or new.tax_regime           is distinct from old.tax_regime
     or new.shipping_method_code is distinct from old.shipping_method_code
     or new.shipping_method_name is distinct from old.shipping_method_name then
    raise exception 'an order''s identity and amounts are immutable'
      using errcode = 'restrict_violation';
  end if;

  -- The one permitted change: a deleted account releases its order.
  if new.user_id is distinct from old.user_id and new.user_id is not null then
    raise exception 'an order cannot be reassigned to another account'
      using errcode = 'restrict_violation';
  end if;

  -- The abuse fingerprint may only ever be cleared, never set or rewritten.
  if new.client_hash is distinct from old.client_hash and new.client_hash is not null then
    raise exception 'the client fingerprint cannot be changed, only cleared'
      using errcode = 'restrict_violation';
  end if;

  -- Since 0013: the payment capability is written once, at creation. It is
  -- never re-issued — a token that can be replaced is one somebody else can
  -- mint for an order they do not hold.
  if old.payment_token_hash is not null
     and new.payment_token_hash is distinct from old.payment_token_hash then
    raise exception 'the payment capability is issued once and cannot be replaced'
      using errcode = 'restrict_violation';
  end if;

  new.updated_at := now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- 3. authorize_order_payment() — may this caller pay for this order?
--
-- Two ways in, and nothing else:
--
--   the account   a signed-in customer paying for their own order
--   the token     whoever holds the capability that was issued at checkout
--
-- Deliberately NOT accepted, each because it is guessable, public, or both:
-- the order number, the order id, the customer's email address, the abuse
-- fingerprint, and the request id.
--
-- `p_user_id` is passed in rather than read from `auth.uid()`, because the
-- caller is an Edge Function running with service credentials — `auth.uid()`
-- would be NULL there. The Edge Function verifies the browser's JWT and hands
-- over the id it proved; this function trusts that boundary and nothing else.
--
-- ON COMPARING HASHES
--
-- The comparison is a plain `=` on two SHA-256 digests, and that is
-- deliberate rather than an oversight. PostgreSQL exposes no constant-time
-- comparison, but none is needed here: what is compared is not the secret but
-- its digest, and an attacker who could measure the comparison byte by byte
-- would learn only about a value they would still have to invert to use. The
-- secret itself never reaches this comparison.
-- ---------------------------------------------------------------------------
create or replace function public.authorize_order_payment(
  p_order_id bigint,
  p_user_id  uuid default null,
  p_token    text default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.orders o
     where o.id = p_order_id
       and (
            -- The account that placed it.
            (p_user_id is not null and o.user_id = p_user_id)
            -- Or the capability issued when it was placed.
         or (
              p_token is not null
              and p_token <> ''
              and o.payment_token_hash is not null
              and o.payment_token_hash = encode(sha256(convert_to(p_token, 'utf8')), 'hex')
            )
       )
  );
$$;

comment on function public.authorize_order_payment(bigint, uuid, text) is
  'Whether this caller may start a payment for this order: the signed-in owner, or the holder of the capability issued at checkout. Never the order number, the order id, the email address, the client fingerprint or the request id — all of those are guessable, public, or both.';

revoke all on function public.authorize_order_payment(bigint, uuid, text)
  from public, anon, authenticated;


-- ---------------------------------------------------------------------------
-- 4. create_order(), now taking a capability — alongside the old signature
--
-- ZERO-DOWNTIME: THE FIVE-ARGUMENT VERSION IS NOT DROPPED
--
-- Replacing it would open a hole for the length of a deployment: the migration
-- lands, Vercel is still serving the previous commit, its checkout calls the
-- five-argument function, and PostgREST answers PGRST202 until the new build
-- goes live. Every checkout in that window fails.
--
-- So both exist for the crossing. They differ in arity **and** in their
-- argument names, and — this is the part that has to be deliberate —
-- `p_payment_token` carries **no DEFAULT**. A default would let a
-- five-name call match both functions, and PostgREST would refuse the call as
-- ambiguous rather than pick one. With no default, each call resolves to
-- exactly one function:
--
--   {request_id, email, items, address, shipping_method}                → old
--   {request_id, email, items, address, shipping_method, payment_token} → new
--
-- The old version is a temporary compatibility shim and nothing more. It is
-- removed by its own migration once the new build is live; see
-- docs/DEPLOYMENT.md.
--
-- THE RETRY PATH IS NOW AN AUTHENTICATION
--
-- This is the whole point of the design. A repeated `request_id` used to hand
-- the order back to anybody who asked. It now hands it back only to a caller
-- who can also present the capability that order was created with — so a
-- retry after a lost response works exactly as before for the browser that
-- made the original call, and gets nothing for anybody else.
--
-- The plaintext token is never stored, never returned and never logged. It
-- goes in, its hash stays, and the caller keeps the copy it already had.
-- ---------------------------------------------------------------------------
create or replace function public.create_order(
  p_request_id      text,
  p_email           text,
  p_items           jsonb,
  p_address         jsonb,
  p_shipping_method text,
  p_payment_token   text
)
returns table (
  order_id        bigint,
  order_number    text,
  items_subtotal  numeric,
  shipping_amount numeric,
  total_amount    numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id bigint;
  v_number   text;
  v_user_id  uuid := (select auth.uid());
  v_item     jsonb;
  v_sky_id   text;
  v_cond     text;
  v_qty      integer;
  v_price    numeric(10,2);
  v_name     text;
  v_image    text;
  v_inv_id   bigint;
  v_subtotal numeric(10,2) := 0;
  v_lines    integer := 0;
  v_client   text;
  v_country  text;
  v_ship_name text;
  v_shipping numeric(10,2);
  v_token_hash text;
  v_existing record;
begin
  if p_request_id is null or length(p_request_id) < 8 then
    raise exception 'a checkout needs a request id' using errcode = 'check_violation';
  end if;

  -- The capability is required. An order nobody can prove they placed is an
  -- order nobody can pay for.
  if p_payment_token is null or length(p_payment_token) < 32 then
    raise exception 'a checkout needs a payment capability' using errcode = 'check_violation';
  end if;

  v_token_hash := encode(sha256(convert_to(p_payment_token, 'utf8')), 'hex');

  -- Already done. Hand it back only to a caller that can prove it is the one
  -- that created it — the same token, not merely the same request id.
  select o.id, o.order_number, o.items_subtotal, o.shipping_amount, o.total_amount,
         o.payment_token_hash
    into v_existing
    from public.orders o
   where o.request_id = p_request_id;

  if found then
    if v_existing.payment_token_hash is distinct from v_token_hash then
      raise exception 'this checkout belongs to somebody else'
        using errcode = 'insufficient_privilege';
    end if;

    order_id        := v_existing.id;
    order_number    := v_existing.order_number;
    items_subtotal  := v_existing.items_subtotal;
    shipping_amount := v_existing.shipping_amount;
    total_amount    := v_existing.total_amount;
    return next;
    return;
  end if;

  if p_email is null or p_email not like '%@%' then
    raise exception 'a checkout needs a contact address' using errcode = 'check_violation';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'a checkout needs at least one article' using errcode = 'check_violation';
  end if;

  v_country := upper(coalesce(p_address ->> 'country_code', ''));
  if v_country <> 'DE' then
    raise exception 'SkyIsles delivers to Germany only' using errcode = 'check_violation';
  end if;

  select c.name into v_ship_name
    from public.shipping_catalog() c
   where c.code = p_shipping_method;

  if v_ship_name is null then
    raise exception 'unknown shipping method %', coalesce(p_shipping_method, '(null)')
      using errcode = 'check_violation';
  end if;

  v_client := public.request_client_hash();
  perform public.enforce_checkout_limits(p_email, v_user_id, v_client);

  insert into public.orders
    (request_id, user_id, customer_email, client_hash, items_subtotal, total_amount,
     shipping_method_code, shipping_method_name, payment_token_hash)
  values
    (p_request_id, v_user_id, p_email, v_client, 0, 0,
     p_shipping_method, v_ship_name, v_token_hash)
  returning id, orders.order_number into v_order_id, v_number;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_sky_id := v_item ->> 'sky_id';
    v_cond   := v_item ->> 'condition';
    v_qty    := nullif(v_item ->> 'quantity', '')::integer;

    if v_qty is null or v_qty < 1 or v_qty > public.max_cart_quantity() then
      raise exception 'invalid quantity for %', v_sky_id using errcode = 'check_violation';
    end if;

    select i.id,
           public.shop_price(i.sale_price, s.market_price, st.price_percentage),
           coalesce(s.display_name_override, s.name),
           coalesce(s.image_override_path, s.image_file)
      into v_inv_id, v_price, v_name, v_image
      from public.shop_inventory i
      join public.skylanders s on s.sky_id = i.sky_id
      cross join public.shop_settings st
     where i.sky_id = v_sky_id
       and i.condition = v_cond
       and i.is_listed
       and public.is_shop_eligible(i.sky_id);

    if v_inv_id is null or v_price is null then
      raise exception 'article % / % is not offered', v_sky_id, v_cond
        using errcode = 'no_data_found';
    end if;

    insert into public.order_lines
      (order_id, sky_id, condition, quantity, name_snapshot, image_snapshot,
       unit_price, line_total, inventory_id)
    values
      (v_order_id, v_sky_id, v_cond, v_qty, v_name, v_image,
       v_price, round(v_price * v_qty, 2), v_inv_id);

    v_subtotal := v_subtotal + round(v_price * v_qty, 2);
    v_lines := v_lines + 1;
  end loop;

  if v_lines = 0 then
    raise exception 'a checkout needs at least one article' using errcode = 'check_violation';
  end if;

  v_shipping := public.shipping_amount_for(p_shipping_method, v_subtotal);

  update public.orders
     set items_subtotal  = v_subtotal,
         shipping_amount = v_shipping,
         total_amount    = v_subtotal + v_shipping
   where id = v_order_id;

  insert into public.order_addresses
    (order_id, kind, first_name, last_name, company, street, house_number,
     address_line_2, postal_code, city, country_code, phone)
  values
    (v_order_id, 'shipping',
     p_address ->> 'first_name', p_address ->> 'last_name', p_address ->> 'company',
     p_address ->> 'street', p_address ->> 'house_number', p_address ->> 'address_line_2',
     p_address ->> 'postal_code', p_address ->> 'city',
     v_country, p_address ->> 'phone');

  perform public.reserve_for_order(v_order_id);

  -- No token, no hash and no fragment of either: an event is a record of what
  -- happened, not a place to leak a secret.
  insert into public.order_events (order_id, event_type, actor_kind, actor_user_id)
  values (v_order_id, 'placed', case when v_user_id is null then 'system' else 'customer' end, v_user_id);

  order_id        := v_order_id;
  order_number    := v_number;
  items_subtotal  := v_subtotal;
  shipping_amount := v_shipping;
  total_amount    := v_subtotal + v_shipping;
  return next;
end;
$$;

comment on function public.create_order(text, text, jsonb, jsonb, text, text) is
  'Creates an order from a cart, stores the hash of the caller''s payment capability, and holds the stock — in one transaction. Prices, shipping and availability come from the database; the caller names a shipping method and a capability, never an amount. A repeated request_id returns the same order only to a caller presenting the same capability. The token itself is never stored, returned or logged.';

revoke all on function public.create_order(text, text, jsonb, jsonb, text, text) from public;
grant execute on function public.create_order(text, text, jsonb, jsonb, text, text) to anon, authenticated;


-- ---------------------------------------------------------------------------
-- 5. The old signature, kept only for the crossing
--
-- Not redefined here — it is exactly what 0011 left, body and grants
-- untouched. All this adds is a note in the database saying what it now is,
-- so nobody finds two `create_order` functions later and has to guess which
-- one matters.
--
-- WHAT AN ORDER PLACED THROUGH IT LOOKS LIKE
--
-- Its INSERT never mentions `payment_token_hash`, so the column stays NULL.
-- That is the honest outcome and deliberately not papered over: no capability
-- was presented, so none is recorded. Inventing one server-side would be worse
-- than useless — a secret whose plaintext nobody holds is not a capability,
-- it is a value that only looks like one.
--
-- The consequence is exactly right: `authorize_order_payment()` requires
-- `payment_token_hash is not null` for the token path, so such an order can
-- **never** be paid by guest capability. A signed-in owner can still pay for
-- it through `user_id`, which is unaffected. And payment is not switched on
-- for anybody during this window anyway.
-- ---------------------------------------------------------------------------
comment on function public.create_order(text, text, jsonb, jsonb, text) is
  'TEMPORARY compatibility shim (0013). The canonical function is the six-argument version that takes a payment capability; this one exists only so the previous deployment keeps working while the new build rolls out. Orders placed through it carry payment_token_hash = NULL and can never be paid by guest capability. Removed by its own migration once the new build is live.';
